/**
 * Seed data for the admin dashboard. Structured the way real API responses
 * would look (flat arrays of objects, ISO dates, foreign-key style IDs) so
 * a real backend is a drop-in replacement later — see `AdminDataContext`,
 * which loads this once and then manages it as in-memory + localStorage
 * state (all "writes" in this dashboard are local-only; nothing is sent
 * anywhere).
 *
 * Content, categories, images and dates were originally reused from the
 * public site's static data (formerly `src/lib/categories.ts`, now removed
 * — the public site fetches real data from the backend instead, see
 * `lib/publicApi.ts`) plus `public/mukalim/` images, rather than invented.
 * This mock layer itself is now only load-bearing for the Settings page and
 * the Topbar's activity dropdown — categories/content/media/users all have
 * their own migrated data source (`lib/admin/api.ts`).
 */

import type {
  ActivityEntry,
  AdminCategory,
  AdminContentItem,
  AdminMediaItem,
  AdminSettings,
  AdminUser,
  LocalizedText,
} from "./types";

function lt(fr: string, en: string, de = "", it = ""): LocalizedText {
  return { fr, en, de, it };
}

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------

export const seedCategories: AdminCategory[] = [
  {
    id: "cosmetics",
    slug: "cosmetics",
    name: lt("Cosmétiques", "Cosmetics", "Kosmetik", "Cosmetici"),
    description: lt(
      "Des ingrédients botaniques conçus pour leur pureté, apportant une vitalité naturelle à des formulations de soin haut de gamme.",
      "Botanical ingredients crafted for purity, bringing natural vitality to premium skincare formulations.",
      "Botanische Inhaltsstoffe für höchste Reinheit, die natürliche Vitalität in Premium-Hautpflegeformulierungen bringen.",
      "Ingredienti botanici curati per la loro purezza, che apportano vitalità naturale a formulazioni di skincare premium.",
    ),
    icon: "/mukalim/icon-cosmetics.svg",
    displayOrder: 1,
    active: true,
    contentCount: 3,
    updatedAt: "2026-08-25",
  },
  {
    id: "food-hygiene",
    slug: "food-hygiene",
    name: lt("Hygiène Alimentaire", "Food Hygiene", "Lebensmittelhygiene", "Igiene Alimentare"),
    description: lt(
      "Des normes rigoureuses et des solutions naturelles garantissant des conditions irréprochables, de la récolte à la manipulation.",
      "Rigorous standards and natural solutions ensuring pristine conditions from harvest to handling.",
      "",
      "Standard rigorosi e soluzioni naturali che garantiscono condizioni impeccabili, dal raccolto alla lavorazione.",
    ),
    icon: "/mukalim/icon-hygiene.svg",
    displayOrder: 2,
    active: true,
    contentCount: 3,
    updatedAt: "2026-08-27",
  },
  {
    id: "food-safety",
    slug: "food-safety",
    name: lt("Sécurité Alimentaire", "Food Safety", "Lebensmittelsicherheit", "Sicurezza Alimentare"),
    description: lt(
      "Des protocoles rigoureusement testés qui garantissent une qualité sans compromis et la protection des consommateurs.",
      "Expertly tested protocols that guarantee uncompromising quality and consumer protection.",
      "Fachkundig getestete Protokolle, die kompromisslose Qualität und Verbraucherschutz garantieren.",
      "",
    ),
    icon: "/mukalim/icon-safety.svg",
    displayOrder: 3,
    active: true,
    contentCount: 3,
    updatedAt: "2026-08-29",
  },
  {
    id: "foods-and-benefits",
    slug: "foods-and-benefits",
    name: lt("Aliments et Bienfaits", "Foods and Benefits", "Lebensmittel und Vorteile", "Alimenti e Benefici"),
    description: lt(
      "L'histoire riche et les bienfaits holistiques des meilleurs ingrédients de la nature, sélectionnés pour la cuisine moderne.",
      "The rich histories and holistic benefits of nature's finest ingredients, curated for the modern kitchen.",
      "",
      "La ricca storia e i benefici olistici dei migliori ingredienti della natura, selezionati per la cucina moderna.",
    ),
    icon: "/mukalim/icon-foods-benefits.svg",
    displayOrder: 4,
    active: true,
    contentCount: 3,
    updatedAt: "2026-08-28",
  },
  {
    id: "impact-of-therapeutic-treatment",
    slug: "impact-of-therapeutic-treatment",
    name: lt(
      "Impact du Traitement Thérapeutique",
      "Impact of Therapeutic Treatment",
      "Wirkung Therapeutischer Behandlung",
      "Impatto del Trattamento Terapeutico",
    ),
    description: lt(
      "Les remèdes traditionnels et la recherche moderne derrière les plantes médicinales les plus respectées de la nature.",
      "Traditional remedies and modern research behind nature's most respected healing botanicals.",
      "Traditionelle Heilmittel und moderne Forschung hinter den angesehensten heilenden Pflanzen der Natur.",
      "",
    ),
    icon: "/mukalim/icon-therapeutic.svg",
    displayOrder: 5,
    active: false,
    contentCount: 3,
    updatedAt: "2026-08-26",
  },
];

// ---------------------------------------------------------------------------
// Content
// ---------------------------------------------------------------------------

export const seedContent: AdminContentItem[] = [
  {
    id: "aloe-vera-the-soothing-botanical",
    categoryId: "cosmetics",
    title: lt("Aloe Vera : La Plante Apaisante", "Aloe Vera: The Soothing Botanical", "Aloe Vera: Die beruhigende Pflanze"),
    featuredImage: "/mukalim/articles/art-aloe.jpg",
    body: lt(
      "Découvrez pourquoi le gel de cette plante succulente est prisé depuis des siècles comme base rafraîchissante et réparatrice pour les peaux sensibles.",
      "Discover why this succulent's gel has been prized for centuries as a cooling, restorative base for sensitive skin formulations.",
    ),
    seoTitle: lt("Aloe Vera : La Plante Apaisante", "Aloe Vera: The Soothing Botanical"),
    seoDescription: lt(
      "Découvrez pourquoi le gel de cette plante succulente est prisé depuis des siècles comme base rafraîchissante et réparatrice pour les peaux sensibles.",
      "Discover why this succulent's gel has been prized for centuries as a cooling, restorative base for sensitive skin formulations.",
    ),
    status: "published",
    author: "Amara Osei",
    updatedAt: "2026-08-25",
  },
  {
    id: "eucalyptus-the-purifying-leaf",
    categoryId: "cosmetics",
    title: lt("Eucalyptus : La Feuille Purifiante", "Eucalyptus: The Purifying Leaf", "", "Eucalipto: La Foglia Purificante"),
    featuredImage: "/mukalim/articles/art-eucalyptus.jpg",
    body: lt(
      "Découvrez les propriétés vives et clarifiantes de l'huile d'eucalyptus et son rôle dans des rituels de soin revigorants et purifiants.",
      "Explore the crisp, clarifying properties of eucalyptus oil and its role in invigorating, purifying skincare rituals.",
    ),
    seoTitle: lt("Eucalyptus : La Feuille Purifiante", "Eucalyptus: The Purifying Leaf"),
    seoDescription: lt(
      "Découvrez les propriétés vives et clarifiantes de l'huile d'eucalyptus et son rôle dans des rituels de soin revigorants et purifiants.",
      "Explore the crisp, clarifying properties of eucalyptus oil and its role in invigorating, purifying skincare rituals.",
    ),
    status: "published",
    author: "Jordan Lee",
    updatedAt: "2026-08-10",
  },
  {
    id: "lavender-the-calming-classic",
    categoryId: "cosmetics",
    title: lt("Lavande : Le Classique Apaisant", "Lavender: The Calming Classic"),
    featuredImage: "/mukalim/articles/art-lavender.jpg",
    body: lt(
      "Explorez l'usage séculaire de la lavande séchée dans les baumes apaisants, et pourquoi son parfum reste un incontournable des soins réparateurs.",
      "Unpack the centuries-old use of dried lavender in soothing balms, and why its aroma remains a staple of restorative skincare.",
    ),
    seoTitle: lt("Lavande : Le Classique Apaisant", "Lavender: The Calming Classic"),
    seoDescription: lt(
      "Explorez l'usage séculaire de la lavande séchée dans les baumes apaisants.",
      "Unpack the centuries-old use of dried lavender in soothing balms.",
    ),
    status: "draft",
    author: "Jordan Lee",
    updatedAt: "2026-07-22",
  },
  {
    id: "cross-contamination-the-silent-risk",
    categoryId: "food-hygiene",
    title: lt(
      "Contamination Croisée : Le Risque Silencieux",
      "Cross-Contamination: The Silent Risk",
      "Kreuzkontamination: Das stille Risiko",
      "Contaminazione Incrociata: Il Rischio Silenzioso",
    ),
    featuredImage: "/mukalim/articles/art-kitchen.jpg",
    body: lt(
      "Comprenez comment les surfaces et outils partagés peuvent compromettre la pureté, et les protocoles que nous suivons pour garder chaque ingrédient isolé et propre.",
      "Understand how shared surfaces and tools can compromise purity, and the protocols we follow to keep every ingredient isolated and clean.",
    ),
    seoTitle: lt("Contamination Croisée : Le Risque Silencieux", "Cross-Contamination: The Silent Risk"),
    seoDescription: lt(
      "Comprenez comment les surfaces et outils partagés peuvent compromettre la pureté.",
      "Understand how shared surfaces and tools can compromise purity.",
    ),
    status: "published",
    author: "Amara Osei",
    updatedAt: "2026-08-27",
  },
  {
    id: "cold-chain-integrity",
    categoryId: "food-hygiene",
    title: lt("Intégrité de la Chaîne du Froid", "Cold Chain Integrity: Why Temperature Matters"),
    featuredImage: "/mukalim/articles/art-jarshelf.jpg",
    body: lt(
      "Découvrez comment un stockage constant et contrôlé préserve la puissance des ingrédients et prévient leur détérioration, de la récolte jusqu'à votre cuisine.",
      "Explore how consistent, controlled storage preserves potency and prevents spoilage from harvest all the way to your kitchen.",
    ),
    seoTitle: lt("Intégrité de la Chaîne du Froid", "Cold Chain Integrity"),
    seoDescription: lt(
      "Découvrez comment un stockage constant et contrôlé préserve la puissance des ingrédients.",
      "Explore how consistent, controlled storage preserves potency.",
    ),
    status: "published",
    author: "Jordan Lee",
    updatedAt: "2026-08-12",
  },
  {
    id: "sanitizing-naturally",
    categoryId: "food-hygiene",
    title: lt(
      "Assainir Naturellement : Antimicrobiens Botaniques",
      "Sanitizing Naturally: Botanical Antimicrobials",
      "Natürlich Desinfizieren: Botanische Antimikrobielle Mittel",
    ),
    featuredImage: "/mukalim/articles/art-essentialoil.jpg",
    body: lt(
      "Découvrez les huiles et extraits d'origine végétale que nous utilisons pour assainir les surfaces sans produits chimiques synthétiques agressifs.",
      "Discover the plant-derived oils and extracts we use to sanitize surfaces without harsh synthetic chemicals.",
    ),
    seoTitle: lt("Assainir Naturellement", "Sanitizing Naturally"),
    seoDescription: lt(
      "Découvrez les huiles et extraits d'origine végétale que nous utilisons pour assainir les surfaces.",
      "Discover the plant-derived oils and extracts we use to sanitize surfaces.",
    ),
    status: "published",
    author: "Amara Osei",
    updatedAt: "2026-07-28",
  },
  {
    id: "haccp-explained",
    categoryId: "food-safety",
    title: lt(
      "HACCP Expliqué : Notre Cadre Qualité",
      "HACCP Explained: Our Quality Framework",
      "HACCP Erklärt: Unser Qualitätsrahmen",
      "HACCP Spiegato: Il Nostro Quadro di Qualità",
    ),
    featuredImage: "/mukalim/articles/art-lab.jpg",
    body: lt(
      "Un aperçu du système d'analyse des risques et de maîtrise des points critiques qui régit chaque lot que nous testons et libérons.",
      "A look inside the Hazard Analysis and Critical Control Points system that governs every batch we test and release.",
    ),
    seoTitle: lt("HACCP Expliqué", "HACCP Explained"),
    seoDescription: lt(
      "Un aperçu du système d'analyse des risques et de maîtrise des points critiques.",
      "A look inside the Hazard Analysis and Critical Control Points system.",
    ),
    status: "published",
    author: "Jordan Lee",
    updatedAt: "2026-08-29",
  },
  {
    id: "traceability-from-farm-to-jar",
    categoryId: "food-safety",
    title: lt(
      "Traçabilité : Du Champ au Bocal",
      "Traceability: From Farm to Jar",
      "",
      "Tracciabilità: Dal Campo al Barattolo",
    ),
    featuredImage: "/mukalim/articles/art-farmer.jpg",
    body: lt(
      "Suivez le parcours d'un seul ingrédient, du champ du producteur jusqu'à l'étagère de votre cuisine, et les registres qui rendent cela possible.",
      "Follow the journey of a single ingredient from the grower's field to your kitchen shelf, and the records that make it possible.",
    ),
    seoTitle: lt("Traçabilité : Du Champ au Bocal", "Traceability: From Farm to Jar"),
    seoDescription: lt(
      "Suivez le parcours d'un seul ingrédient, du champ du producteur jusqu'à l'étagère de votre cuisine.",
      "Follow the journey of a single ingredient from the grower's field to your kitchen shelf.",
    ),
    status: "published",
    author: "Amara Osei",
    updatedAt: "2026-08-18",
  },
  {
    id: "allergen-control",
    categoryId: "food-safety",
    title: lt("Contrôle des Allergènes", "Allergen Control: Protecting Every Batch"),
    featuredImage: "/mukalim/articles/art-pantryjars.jpg",
    body: lt(
      "Comprenez les protocoles d'étiquetage et de contact croisé qui protègent les consommateurs sensibles sans compromettre la saveur.",
      "Understand the labeling and cross-contact protocols that protect sensitive consumers without compromising flavor.",
    ),
    seoTitle: lt("Contrôle des Allergènes", "Allergen Control"),
    seoDescription: lt(
      "Comprenez les protocoles d'étiquetage et de contact croisé qui protègent les consommateurs sensibles.",
      "Understand the labeling and cross-contact protocols that protect sensitive consumers.",
    ),
    status: "draft",
    author: "Jordan Lee",
    updatedAt: "2026-08-02",
  },
  {
    id: "turmeric-the-golden-healer",
    categoryId: "foods-and-benefits",
    title: lt(
      "Curcuma : Le Guérisseur Doré",
      "Turmeric: The Golden Healer",
      "Kurkuma: Der Goldene Heiler",
      "Curcuma: Il Guaritore Dorato",
    ),
    featuredImage: "/mukalim/articles/art-turmeric.jpg",
    body: lt(
      "Découvrez les puissantes propriétés anti-inflammatoires de la curcumine et comment intégrer cette racine ancestrale à votre rituel de bien-être quotidien.",
      "Discover the powerful anti-inflammatory properties of curcumin and how to integrate this ancient root into your daily wellness ritual.",
    ),
    seoTitle: lt("Curcuma : Le Guérisseur Doré", "Turmeric: The Golden Healer"),
    seoDescription: lt(
      "Découvrez les puissantes propriétés anti-inflammatoires de la curcumine.",
      "Discover the powerful anti-inflammatory properties of curcumin.",
    ),
    status: "published",
    author: "Amara Osei",
    updatedAt: "2026-08-28",
  },
  {
    id: "cardamom-queen-of-spices",
    categoryId: "foods-and-benefits",
    title: lt("Cardamome : La Reine des Épices", "Cardamom: Queen of Spices", "Kardamom: Königin der Gewürze"),
    featuredImage: "/mukalim/articles/art-cardamom.jpg",
    body: lt(
      "Explorez le profil aromatique complexe de la cardamome, ses bienfaits digestifs, et pourquoi elle occupe une place vénérée dans les traditions sucrées comme salées.",
      "Explore the complex flavor profile of cardamom, its digestive benefits, and why it holds a revered place in both sweet and savory traditions.",
    ),
    seoTitle: lt("Cardamome : La Reine des Épices", "Cardamom: Queen of Spices"),
    seoDescription: lt(
      "Explorez le profil aromatique complexe de la cardamome et ses bienfaits digestifs.",
      "Explore the complex flavor profile of cardamom and its digestive benefits.",
    ),
    status: "published",
    author: "Jordan Lee",
    updatedAt: "2026-08-15",
  },
  {
    id: "matcha-antioxidant-powerhouse",
    categoryId: "foods-and-benefits",
    title: lt("Matcha : Concentré d'Antioxydants", "Matcha: Antioxidant Powerhouse", "", "Matcha: Concentrato di Antiossidanti"),
    featuredImage: "/mukalim/articles/art-matcha.jpg",
    body: lt(
      "Explorez la science derrière la L-théanine et les catéchines présentes dans le matcha de qualité cérémoniale, et son effet apaisant sur la concentration et l'énergie.",
      "Unpack the science behind L-theanine and catechins found in ceremonial grade matcha, and its calming effect on focus and energy.",
    ),
    seoTitle: lt("Matcha : Concentré d'Antioxydants", "Matcha: Antioxidant Powerhouse"),
    seoDescription: lt(
      "Explorez la science derrière la L-théanine et les catéchines présentes dans le matcha.",
      "Unpack the science behind L-theanine and catechins found in ceremonial grade matcha.",
    ),
    status: "published",
    author: "Amara Osei",
    updatedAt: "2026-07-30",
  },
  {
    id: "ginger-ancient-remedy",
    categoryId: "impact-of-therapeutic-treatment",
    title: lt(
      "Gingembre : Remède Ancestral",
      "Ginger: Ancient Remedy for Modern Wellness",
      "Ingwer: Altes Heilmittel für Modernes Wohlbefinden",
      "Zenzero: Rimedio Ancestrale per il Benessere Moderno",
    ),
    featuredImage: "/mukalim/articles/art-ginger.jpg",
    body: lt(
      "Découvrez pourquoi cette racine chauffante ancre la médecine traditionnelle depuis des millénaires, et ce que la recherche moderne révèle sur ses bienfaits.",
      "Discover why this warming root has anchored traditional medicine for millennia, and what modern research reveals about its benefits.",
    ),
    seoTitle: lt("Gingembre : Remède Ancestral", "Ginger: Ancient Remedy"),
    seoDescription: lt(
      "Découvrez pourquoi cette racine chauffante ancre la médecine traditionnelle depuis des millénaires.",
      "Discover why this warming root has anchored traditional medicine for millennia.",
    ),
    status: "published",
    author: "Jordan Lee",
    updatedAt: "2026-08-26",
  },
  {
    id: "star-anise-the-digestive-aid",
    categoryId: "impact-of-therapeutic-treatment",
    title: lt("Anis Étoilé : L'Aide Digestive", "Star Anise: The Digestive Aid"),
    featuredImage: "/mukalim/articles/art-staranise.jpg",
    body: lt(
      "Explorez l'usage traditionnel de l'anis étoilé pour apaiser la digestion, et les composés aromatiques à l'origine de sa réputation thérapeutique.",
      "Explore the traditional use of star anise in soothing digestion, and the aromatic compounds behind its therapeutic reputation.",
    ),
    seoTitle: lt("Anis Étoilé : L'Aide Digestive", "Star Anise: The Digestive Aid"),
    seoDescription: lt(
      "Explorez l'usage traditionnel de l'anis étoilé pour apaiser la digestion.",
      "Explore the traditional use of star anise in soothing digestion.",
    ),
    status: "draft",
    author: "Amara Osei",
    updatedAt: "2026-08-14",
  },
  {
    id: "ashwagandha-the-adaptogen-herb",
    categoryId: "impact-of-therapeutic-treatment",
    title: lt("Ashwagandha : La Plante Adaptogène", "Ashwagandha: The Adaptogen Herb", "", "Ashwagandha: L'Erba Adattogena"),
    featuredImage: "/mukalim/articles/art-ashwagandha.jpg",
    body: lt(
      "Explorez la science derrière cet adaptogène vénéré et son rôle traditionnel dans le soutien de la réponse du corps au stress.",
      "Unpack the science behind this revered adaptogen and its traditional role in supporting the body's response to stress.",
    ),
    seoTitle: lt("Ashwagandha : La Plante Adaptogène", "Ashwagandha: The Adaptogen Herb"),
    seoDescription: lt(
      "Explorez la science derrière cet adaptogène vénéré.",
      "Unpack the science behind this revered adaptogen.",
    ),
    status: "published",
    author: "Jordan Lee",
    updatedAt: "2026-07-31",
  },
];

// ---------------------------------------------------------------------------
// Media
// ---------------------------------------------------------------------------

export const seedMedia: AdminMediaItem[] = [
  {
    id: "logo",
    filename: "logo.png",
    url: "/mukalim/logo.png",
    sizeKb: 1,
    width: 80,
    height: 80,
    usedIn: ["Site header", "Sign-in page"],
    altText: lt("Logo de la marque Mukalim", "Mukalim brand logo", "Mukalim Markenlogo", "Logo del marchio Mukalim"),
    uploadedAt: "2026-06-01",
  },
  {
    id: "hero",
    filename: "hero.jpg",
    url: "/mukalim/hero.jpg",
    sizeKb: 1500,
    width: 2400,
    height: 3600,
    usedIn: ["Homepage hero"],
    altText: lt(
      "Vue aérienne de bols remplis d'épices colorées",
      "Overhead view of bowls filled with colorful spices",
      "",
      "",
    ),
    uploadedAt: "2026-06-03",
  },
  {
    id: "card-cosmetics",
    filename: "card-cosmetics.jpg",
    url: "/mukalim/card-cosmetics.jpg",
    sizeKb: 268,
    width: 1400,
    height: 804,
    usedIn: ["Cosmetics category card"],
    altText: lt("Bocaux d'extraits d'herbes séchées", "Glass jars of dried herbal extracts", "", ""),
    uploadedAt: "2026-06-05",
  },
  {
    id: "card-hygiene",
    filename: "card-hygiene.jpg",
    url: "/mukalim/card-hygiene.jpg",
    sizeKb: 354,
    width: 1400,
    height: 2100,
    usedIn: ["Food Hygiene category card", "Food Hygiene category hero"],
    altText: lt("Comptoir de cuisine propre et moderne", "A clean, modern kitchen counter", "Sauberer, moderner Küchentresen", ""),
    uploadedAt: "2026-06-05",
  },
  {
    id: "card-safety",
    filename: "card-safety.jpg",
    url: "/mukalim/card-safety.jpg",
    sizeKb: 195,
    width: 1400,
    height: 1867,
    usedIn: ["Food Safety category card", "Food Safety category hero"],
    altText: lt("Bâtons de cannelle et épices séchées", "Cinnamon sticks and dried spices", "", "Bastoncini di cannella e spezie essiccate"),
    uploadedAt: "2026-06-05",
  },
  {
    id: "trust",
    filename: "trust.jpg",
    url: "/mukalim/trust.jpg",
    sizeKb: 230,
    width: 1600,
    height: 1067,
    usedIn: ["Homepage trust section", "Impact of Therapeutic Treatment category hero"],
    altText: lt(
      "Mains ridées broyant des épices dans un mortier",
      "Weathered hands grinding spices with a mortar and pestle",
      "Verwitterte Hände zerstoßen Gewürze mit Mörser und Stößel",
      "",
    ),
    uploadedAt: "2026-06-08",
  },
  {
    id: "cosmetics-hero",
    filename: "cosmetics-hero.jpg",
    url: "/mukalim/articles/cosmetics-hero.jpg",
    sizeKb: 1273,
    width: 2000,
    height: 3000,
    usedIn: ["Cosmetics category hero"],
    altText: lt(
      "Bouquets de plantes séchées suspendus à un étal de marché",
      "Bundles of dried botanicals hanging at a market stall",
      "",
      "",
    ),
    uploadedAt: "2026-08-01",
  },
  {
    id: "fb-hero",
    filename: "fb-hero.jpg",
    url: "/mukalim/articles/fb-hero.jpg",
    sizeKb: 1607,
    width: 2000,
    height: 3000,
    usedIn: ["Foods and Benefits category card", "Foods and Benefits category hero"],
    altText: lt(
      "Une ruelle couverte d'un marché aux épices",
      "A covered alley in a spice market lined with stalls",
      "Eine überdachte Gasse auf einem Gewürzmarkt",
      "",
    ),
    uploadedAt: "2026-08-01",
  },
  {
    id: "art-turmeric",
    filename: "art-turmeric.jpg",
    url: "/mukalim/articles/art-turmeric.jpg",
    sizeKb: 308,
    width: 1000,
    height: 1778,
    usedIn: ["'Turmeric: The Golden Healer' article"],
    altText: lt("Tas d'épices colorées moulues sur un marché", "Piles of colorful ground spices at a spice market", "", "Mucchi di spezie macinate colorate al mercato"),
    uploadedAt: "2026-08-02",
  },
  {
    id: "art-cardamom",
    filename: "art-cardamom.jpg",
    url: "/mukalim/articles/art-cardamom.jpg",
    sizeKb: 91,
    width: 1000,
    height: 669,
    usedIn: ["'Cardamom: Queen of Spices' article"],
    altText: lt("Un tas de gousses de cardamome séchées", "A pile of dried cardamom pods", "Ein Haufen getrockneter Kardamomkapseln", ""),
    uploadedAt: "2026-08-02",
  },
  {
    id: "art-matcha",
    filename: "art-matcha.jpg",
    url: "/mukalim/articles/art-matcha.jpg",
    sizeKb: 153,
    width: 1000,
    height: 1499,
    usedIn: ["'Matcha: Antioxidant Powerhouse' article"],
    altText: lt("Poudre de matcha avec fouet en bambou", "Matcha powder with a bamboo whisk and chopsticks", "", ""),
    uploadedAt: "2026-08-02",
  },
  {
    id: "art-aloe",
    filename: "art-aloe.jpg",
    url: "/mukalim/articles/art-aloe.jpg",
    sizeKb: 66,
    width: 1000,
    height: 667,
    usedIn: ["'Aloe Vera: The Soothing Botanical' article"],
    altText: lt("Gros plan de feuilles d'aloe vera", "Close-up of aloe vera plant leaves", "Nahaufnahme von Aloe-Vera-Blättern", ""),
    uploadedAt: "2026-08-03",
  },
  {
    id: "art-eucalyptus",
    filename: "art-eucalyptus.jpg",
    url: "/mukalim/articles/art-eucalyptus.jpg",
    sizeKb: 64,
    width: 1000,
    height: 1500,
    usedIn: ["'Eucalyptus: The Purifying Leaf' article"],
    altText: lt("Branche d'eucalyptus sur fond neutre", "Eucalyptus branch against a neutral backdrop", "", "Ramo di eucalipto su sfondo neutro"),
    uploadedAt: "2026-08-03",
  },
  {
    id: "art-lavender",
    filename: "art-lavender.jpg",
    url: "/mukalim/articles/art-lavender.jpg",
    sizeKb: 117,
    width: 1000,
    height: 667,
    usedIn: ["'Lavender: The Calming Classic' article"],
    altText: lt("Un bouquet de fleurs de lavande séchées", "A bundle of dried lavender flowers", "", ""),
    uploadedAt: "2026-08-03",
  },
  {
    id: "art-kitchen",
    filename: "art-kitchen.jpg",
    url: "/mukalim/articles/art-kitchen.jpg",
    sizeKb: 92,
    width: 1000,
    height: 667,
    usedIn: ["'Cross-Contamination: The Silent Risk' article"],
    altText: lt("Cuisine propre et moderne avec armoires", "A clean, modern kitchen counter and cabinetry", "Saubere, moderne Küche mit Schränken", ""),
    uploadedAt: "2026-08-04",
  },
  {
    id: "art-jarshelf",
    filename: "art-jarshelf.jpg",
    url: "/mukalim/articles/art-jarshelf.jpg",
    sizeKb: 166,
    width: 1000,
    height: 667,
    usedIn: ["'Cold Chain Integrity' article"],
    altText: lt("Rangées de bocaux d'apothicaire sur une étagère", "Rows of glass apothecary jars on a shelf", "", ""),
    uploadedAt: "2026-08-04",
  },
  {
    id: "art-essentialoil",
    filename: "art-essentialoil.jpg",
    url: "/mukalim/articles/art-essentialoil.jpg",
    sizeKb: 55,
    width: 1000,
    height: 667,
    usedIn: ["'Sanitizing Naturally' article"],
    altText: lt("Une main tenant une petite bouteille d'huile essentielle", "A hand holding a small bottle of essential oil", "", "Una mano che tiene una piccola bottiglia di olio essenziale"),
    uploadedAt: "2026-08-04",
  },
  {
    id: "art-lab",
    filename: "art-lab.jpg",
    url: "/mukalim/articles/art-lab.jpg",
    sizeKb: 87,
    width: 1000,
    height: 627,
    usedIn: ["'HACCP Explained' article"],
    altText: lt("Un technicien de laboratoire testant des échantillons", "A lab technician testing samples with a pipette", "Ein Labortechniker testet Proben mit einer Pipette", ""),
    uploadedAt: "2026-08-05",
  },
  {
    id: "art-farmer",
    filename: "art-farmer.jpg",
    url: "/mukalim/articles/art-farmer.jpg",
    sizeKb: 171,
    width: 1000,
    height: 667,
    usedIn: ["'Traceability: From Farm to Jar' article"],
    altText: lt("Un agriculteur travaillant dans un champ vert", "A farmer working in a green field", "", ""),
    uploadedAt: "2026-08-05",
  },
  {
    id: "art-pantryjars",
    filename: "art-pantryjars.jpg",
    url: "/mukalim/articles/art-pantryjars.jpg",
    sizeKb: 315,
    width: 1000,
    height: 1500,
    usedIn: ["'Allergen Control' article"],
    altText: lt("Rangées de bocaux étiquetés de conserves", "Rows of labeled jars of preserved foods", "", "File di barattoli etichettati di conserve"),
    uploadedAt: "2026-08-05",
  },
  {
    id: "art-ginger",
    filename: "art-ginger.jpg",
    url: "/mukalim/articles/art-ginger.jpg",
    sizeKb: 241,
    width: 1000,
    height: 1500,
    usedIn: ["'Ginger: Ancient Remedy' article"],
    altText: lt("Un tas de racines de gingembre frais", "A pile of fresh ginger root", "Ein Haufen frischer Ingwerwurzeln", ""),
    uploadedAt: "2026-08-06",
  },
  {
    id: "art-staranise",
    filename: "art-staranise.jpg",
    url: "/mukalim/articles/art-staranise.jpg",
    sizeKb: 168,
    width: 1000,
    height: 667,
    usedIn: ["'Star Anise: The Digestive Aid' article"],
    altText: lt("Gros plan de gousses d'anis étoilé entières", "Close-up of whole star anise pods", "", ""),
    uploadedAt: "2026-08-06",
  },
  {
    id: "art-ashwagandha",
    filename: "art-ashwagandha.jpg",
    url: "/mukalim/articles/art-ashwagandha.jpg",
    sizeKb: 81,
    width: 1000,
    height: 662,
    usedIn: ["'Ashwagandha: The Adaptogen Herb' article"],
    altText: lt("Feuilles vertes de la plante ashwagandha", "Green ashwagandha plant leaves", "Grüne Blätter der Ashwagandha-Pflanze", ""),
    uploadedAt: "2026-08-06",
  },
];

// ---------------------------------------------------------------------------
// Users
// ---------------------------------------------------------------------------

export const seedUsers: AdminUser[] = [
  {
    id: "u1",
    name: "Amara Osei",
    email: "amara@mukalim.com",
    role: "admin",
    status: "active",
    lastLogin: "2026-09-01T08:12:00",
    avatarColor: "bg-brand-gold",
  },
  {
    id: "u2",
    name: "Jordan Lee",
    email: "jordan@mukalim.com",
    role: "editor",
    status: "active",
    lastLogin: "2026-08-31T16:45:00",
    avatarColor: "bg-admin-terracotta",
  },
  {
    id: "u3",
    name: "Priya Nair",
    email: "priya@mukalim.com",
    role: "editor",
    status: "invited",
    lastLogin: null,
    avatarColor: "bg-admin-green",
  },
  {
    id: "u4",
    name: "Sam Whitfield",
    email: "sam@mukalim.com",
    role: "viewer",
    status: "active",
    lastLogin: "2026-08-29T11:20:00",
    avatarColor: "bg-brand-brown",
  },
  {
    id: "u5",
    name: "Chidi Okafor",
    email: "chidi@mukalim.com",
    role: "viewer",
    status: "disabled",
    lastLogin: "2026-07-14T09:03:00",
    avatarColor: "bg-admin-warm-grey",
  },
];

// ---------------------------------------------------------------------------
// Activity feed
// ---------------------------------------------------------------------------

export const seedActivity: ActivityEntry[] = [
  {
    id: "a1",
    actor: "Amara Osei",
    actorRole: "admin",
    action: "published",
    target: "'Turmeric: The Golden Healer'",
    timestamp: "2026-09-01T06:30:00",
  },
  {
    id: "a2",
    actor: "Jordan Lee",
    actorRole: "editor",
    action: "updated the",
    target: "Cosmetics category",
    timestamp: "2026-09-01T04:15:00",
  },
  {
    id: "a3",
    actor: "Jordan Lee",
    actorRole: "editor",
    action: "set to draft",
    target: "'Star Anise: The Digestive Aid'",
    timestamp: "2026-08-31T14:50:00",
  },
  {
    id: "a4",
    actor: "Amara Osei",
    actorRole: "admin",
    action: "uploaded 3 new images to",
    target: "Media Library",
    timestamp: "2026-08-31T09:05:00",
  },
  {
    id: "a5",
    actor: "Amara Osei",
    actorRole: "admin",
    action: "invited",
    target: "Priya Nair as Editor",
    timestamp: "2026-08-30T17:40:00",
  },
  {
    id: "a6",
    actor: "Jordan Lee",
    actorRole: "editor",
    action: "updated",
    target: "'HACCP Explained: Our Quality Framework'",
    timestamp: "2026-08-29T13:22:00",
  },
  {
    id: "a7",
    actor: "Amara Osei",
    actorRole: "admin",
    action: "set to inactive the",
    target: "Impact of Therapeutic Treatment category",
    timestamp: "2026-08-26T10:10:00",
  },
];

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

export const seedSettings: AdminSettings = {
  siteName: "Mukalim",
  defaultLanguage: "en",
  contactEmail: "hello@mukalim.com",
  social: {
    instagram: "https://instagram.com/mukalim",
    facebook: "https://facebook.com/mukalim",
    linkedin: "https://linkedin.com/company/mukalim",
  },
};
